### ISSUE TITLE
Summary - Exceeds Expectations

### ISSUE THREAD

**Issue by jlag34** [webbstandard/bwa-u4-feature-request#1]
Your feature request was done really well. Great job including all four parts, objective, background, technical design, and caveats. This is great feature because people assume hitting `enter` will just work. I like your implementation on how to design the code. Reading it over, I could definitely understand and code what you needed quickly. It would have been nice to see that you added a little bit of code into it, especially with it being a fairly easy implementation. Lastly, nice job with your caveats. You covered your edge cases well. In my opinion, a little if code isn't 100% DRY it's ok if it makes it easier for others to read and understand. All in all, good work on this project.

**Comment by webbstandard** [comment]
Thanks, @jlag34!

**Comment by webbstandard** [comment]
Thanks, @jlag34!
